// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: swampy.proto

package swampyservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SwampyServiceClient is the client API for SwampyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwampyServiceClient interface {
	ScheduleProduceMsg(ctx context.Context, in *ScheduleProduceMsgRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type swampyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwampyServiceClient(cc grpc.ClientConnInterface) SwampyServiceClient {
	return &swampyServiceClient{cc}
}

func (c *swampyServiceClient) ScheduleProduceMsg(ctx context.Context, in *ScheduleProduceMsgRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/message.SwampyService/ScheduleProduceMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwampyServiceServer is the server API for SwampyService service.
// All implementations must embed UnimplementedSwampyServiceServer
// for forward compatibility
type SwampyServiceServer interface {
	ScheduleProduceMsg(context.Context, *ScheduleProduceMsgRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSwampyServiceServer()
}

// UnimplementedSwampyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSwampyServiceServer struct {
}

func (UnimplementedSwampyServiceServer) ScheduleProduceMsg(context.Context, *ScheduleProduceMsgRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleProduceMsg not implemented")
}
func (UnimplementedSwampyServiceServer) mustEmbedUnimplementedSwampyServiceServer() {}

// UnsafeSwampyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwampyServiceServer will
// result in compilation errors.
type UnsafeSwampyServiceServer interface {
	mustEmbedUnimplementedSwampyServiceServer()
}

func RegisterSwampyServiceServer(s grpc.ServiceRegistrar, srv SwampyServiceServer) {
	s.RegisterService(&SwampyService_ServiceDesc, srv)
}

func _SwampyService_ScheduleProduceMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleProduceMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwampyServiceServer).ScheduleProduceMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.SwampyService/ScheduleProduceMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwampyServiceServer).ScheduleProduceMsg(ctx, req.(*ScheduleProduceMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwampyService_ServiceDesc is the grpc.ServiceDesc for SwampyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwampyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.SwampyService",
	HandlerType: (*SwampyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleProduceMsg",
			Handler:    _SwampyService_ScheduleProduceMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swampy.proto",
}
